Repository Esgariot/DigitalDocuments_Bookstore, pull requests merged in 2018-11, with the labels that each got.

#45 C# library for sending & receiving emails.
  Examples/CSharpEmailLibrary/CSharpEmailLibrary.sln
  Examples/CSharpEmailLibrary/CSharpEmailLibrary/CSharpEmailLibrary.csproj
  Examples/CSharpEmailLibrary/CSharpEmailLibrary/Mail.cs
  Examples/CSharpEmailLibrary/CSharpEmailLibrary/MailReceiver.cs
  Examples/CSharpEmailLibrary/CSharpEmailLibrary/MailSender.cs
  Examples/CSharpEmailLibrary/CSharpEmailLibrary/MailsCredentials.cs
  Examples/CSharpEmailLibrary/Tools/OpenPop.dll
  GUI/GUI_Prototype/GUI_Prototype.csproj
  GUI/GUI_Prototype/MainWindow.xaml
  GUI/GUI_Prototype/WorkersSelectionWindow.xaml.cs
  GUI/Tools/CSharpEmailLibrary.dll
Labels: Sprint4

#46 added c# class to work on XPDL file
  Examples/XPDLReader/XPDLReader.sln
  Examples/XPDLReader/XPDLReader/App.config
  Examples/XPDLReader/XPDLReader/Program.cs
  Examples/XPDLReader/XPDLReader/Properties/AssemblyInfo.cs
  Examples/XPDLReader/XPDLReader/XPDLManager.cs
  Examples/XPDLReader/XPDLReader/XPDLReader.csproj
  Examples/XPDLReader/xpdl.xml
Labels: Sprint4

#59 File archive for transactions
  Examples/FileArchiveExample/FileArchiveExample.sln
  Examples/FileArchiveExample/FileArchiveExample/App.config
  Examples/FileArchiveExample/FileArchiveExample/Archive.cs
  Examples/FileArchiveExample/FileArchiveExample/FileArchiveExample.csproj
  Examples/FileArchiveExample/FileArchiveExample/Program.cs
  Examples/FileArchiveExample/FileArchiveExample/Properties/AssemblyInfo.cs
  Examples/FileArchiveExample/Tools/LiteDB.dll
  Examples/FileArchiveExample/Tools/PurchaseOrderTemplate.xml
  Examples/FileArchiveExample/Tools/XPDL.txt
  FileArchiveClient/FileArchiveClient.sln
  FileArchiveClient/FileArchiveClient/App.config
  FileArchiveClient/FileArchiveClient/Archive.cs
  FileArchiveClient/FileArchiveClient/FileArchiveClient.csproj
  FileArchiveClient/FileArchiveClient/Form1.Designer.cs
  FileArchiveClient/FileArchiveClient/Form1.cs
  FileArchiveClient/FileArchiveClient/Form1.resx
  FileArchiveClient/FileArchiveClient/Program.cs
  FileArchiveClient/FileArchiveClient/Properties/AssemblyInfo.cs
  FileArchiveClient/FileArchiveClient/Properties/Resources.Designer.cs
  FileArchiveClient/FileArchiveClient/Properties/Resources.resx
  FileArchiveClient/FileArchiveClient/Properties/Settings.Designer.cs
  FileArchiveClient/FileArchiveClient/Properties/Settings.settings
  FileArchiveClient/Tools/LiteDB.dll
  GUI/GUI_Prototype/Archive.cs
  GUI/GUI_Prototype/GUI_Prototype.csproj
  GUI/GUI_Prototype/MainWindow.xaml.cs
  GUI/Tools/LiteDB.dll
Labels: Sprint5

#67 utworzenie xpdla do modyfikacji w bin/Debug; podpiecie biblioteki xpd…
  GUI/GUI_Prototype/GUI_Prototype.csproj
  GUI/GUI_Prototype/MainWindow.xaml.cs
  GUI/GUI_Prototype/Utils.cs
  GUI/GUI_Prototype/XPDLManager.cs
  GUI/GUI_Prototype/xpdl_template.xml
Labels: Work in progress
